"""Writing decisions back into DataHub.

At the end of a session Zence upserts one **decision document** into DataHub,
linked to the assets involved, plus a `zence.last_review` structured property on
each of them. That is the "beyond reading metadata" half of the integration: the
catalog learns something it did not know, and the next person to look at
`bluepeak.patient_contacts` sees that an agent session was stopped from reaching
it, when, and under which rule.

**Idempotency is structural, not defensive.** The document id is a hash of
workspace and session, so upserting twice updates one record. There is no
"check if it exists first" round trip to lose a race against, and finalizing a
session ten times leaves exactly one document — which is the property the
hackathon asks to see demonstrated.

Nothing here mutates a client's own metadata. Zence does not retag, reclassify,
or reassign ownership of anyone's assets; it records its own findings alongside
them and says who wrote them.
"""

from __future__ import annotations

import hashlib
import warnings
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

#: Where decision documents are filed in DataHub.
DOCUMENT_SUBTYPE = "Decision Record"

#: Structured property carrying the most recent review of an asset.
REVIEW_PROPERTY = "zence.last_review"

#: Stamped into every document so its provenance is never ambiguous.
PROVENANCE = "Generated by Zence — https://zence.site"


def idempotency_key(workspace_id: str, session_id: str) -> str:
    """A stable id for one session's decision record.

    Derived only from inputs that do not change within a session, so every
    finalization during that session targets the same document. Truncated to 16
    hex characters: enough that a collision is not a practical concern, short
    enough that the URN stays readable in a catalog UI.
    """
    digest = hashlib.sha256(f"{workspace_id}::{session_id}".encode()).hexdigest()
    return f"zence-session-{digest[:16]}"


@dataclass(frozen=True, slots=True)
class WriteBackResult:
    ok: bool
    idempotency_key: str
    document_urn: str | None = None
    detail: str = ""
    properties_written: int = 0


def _render(
    *,
    client_name: str,
    workspace_id: str,
    session_id: str,
    repository: str,
    policy_version: str,
    decisions: Sequence[dict[str, Any]],
) -> str:
    """The document body, as markdown.

    Written for the person who finds it in DataHub six weeks later with no
    memory of the session, so it leads with what was stopped rather than with a
    table of counts.
    """
    now = datetime.now(UTC).isoformat(timespec="seconds")

    blocked = [d for d in decisions if d["verdict"] == "deny"]
    asked = [d for d in decisions if d["verdict"] == "ask"]
    allowed = [d for d in decisions if d["verdict"] == "allow"]

    lines = [
        f"# Zence session review — {client_name}",
        "",
        f"An agent session in `{repository}` was evaluated against this catalog. "
        f"{len(decisions)} operation(s) reached a decision: "
        f"**{len(blocked)} blocked**, {len(asked)} sent for approval, {len(allowed)} allowed.",
        "",
        "| | |",
        "|---|---|",
        f"| Client boundary | {client_name} |",
        f"| Workspace | `{workspace_id}` |",
        f"| Repository | `{repository}` |",
        f"| Session | `{session_id}` |",
        f"| Policy version | {policy_version} |",
        f"| Recorded | {now} |",
        "",
    ]

    if blocked:
        lines += ["## Blocked", ""]
        for decision in blocked:
            lines += _entry(decision)

    if asked:
        lines += ["## Sent for approval", ""]
        for decision in asked:
            lines += _entry(decision)

    if allowed:
        lines += [
            "## Allowed",
            "",
            f"{len(allowed)} operation(s) resolved inside {client_name} and were "
            "permitted. Listed by rule rather than individually:",
            "",
        ]
        by_rule: dict[str, int] = {}
        for decision in allowed:
            key = f"{decision['rule_id']} {decision['rule_title']}"
            by_rule[key] = by_rule.get(key, 0) + 1
        lines += [f"- {rule} — {count}" for rule, count in sorted(by_rule.items())]
        lines.append("")

    lines += ["---", "", PROVENANCE]
    return "\n".join(lines)


def _entry(decision: dict[str, Any]) -> list[str]:
    import json

    urns = json.loads(decision.get("evidence_urns") or "[]")
    lines = [
        f"### {decision['rule_id']} — {decision['rule_title']}",
        "",
        decision["reason"],
        "",
    ]
    if urns:
        lines += ["Assets:", ""]
        lines += [f"- `{urn}`" for urn in urns]
        lines.append("")
    if decision.get("remediation"):
        lines += [f"**Suggested instead:** {decision['remediation']}", ""]
    if decision.get("degraded"):
        lines += [
            "> Decided with incomplete metadata — DataHub was unreachable at the time.",
            "",
        ]
    if decision.get("would_have_been"):
        lines += [
            f"> Audit mode: enforce would have returned `{decision['would_have_been']}`.",
            "",
        ]
    return lines


def write_session_document(
    *,
    server: str,
    token: str | None,
    client_name: str,
    workspace_id: str,
    session_id: str,
    repository: str,
    policy_version: str,
    decisions: Sequence[dict[str, Any]],
    related_urns: Sequence[str] = (),
    timeout_seconds: float = 10.0,
) -> WriteBackResult:
    """Upsert the session's decision document. Never raises."""
    key = idempotency_key(workspace_id, session_id)

    if not decisions:
        return WriteBackResult(ok=False, idempotency_key=key, detail="nothing to record")

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            from datahub.ingestion.graph.client import DatahubClientConfig

            # `datahub.sdk` re-exports lazily through __getattr__, so these are
            # invisible to static analysis even though they resolve at runtime.
            from datahub.sdk import DataHubClient, Document  # type: ignore[attr-defined]
    except ImportError:
        return WriteBackResult(
            ok=False,
            idempotency_key=key,
            detail="the DataHub SDK is not installed (uv sync --extra datahub)",
        )

    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            # No retries, same as the read path. The SDK retries with backoff by
            # default, which turned an unreachable catalog into a 28-second stall
            # inside the Stop hook — long enough to feel like Claude Code hung at
            # the end of every session.
            client = DataHubClient(
                config=DatahubClientConfig(
                    server=server,
                    token=token,
                    timeout_sec=timeout_seconds,
                    retry_max_times=0,
                )
            )

            document = Document.create_document(
                id=key,
                title=f"Zence session review — {client_name}",
                text=_render(
                    client_name=client_name,
                    workspace_id=workspace_id,
                    session_id=session_id,
                    repository=repository,
                    policy_version=policy_version,
                    decisions=decisions,
                ),
                subtype=DOCUMENT_SUBTYPE,
                related_assets=list(dict.fromkeys(related_urns)) or None,
                custom_properties={
                    "zence.workspace": workspace_id,
                    "zence.session": session_id,
                    "zence.policy_version": policy_version,
                    "zence.decisions": str(len(decisions)),
                    "zence.idempotency_key": key,
                },
            )
            client.entities.upsert(document)
    except Exception as exc:
        return WriteBackResult(ok=False, idempotency_key=key, detail=f"write-back failed: {exc}")

    return WriteBackResult(
        ok=True,
        idempotency_key=key,
        document_urn=str(getattr(document, "urn", key)),
        detail="document upserted",
    )
