/*
  The Zence mark.

  Geometry generated by `brand/build.py` from the supplied artwork and verified
  against it pixel-by-pixel by `brand/verify.py` — do not hand-edit the numbers
  here. Regenerate and paste if the mark ever changes.

  The standalone files in `public/` and `app/icon.svg` carry their colours
  inline, because a favicon is a separate document that cannot see this page.
  This component instead paints from `--color-brand-*`, so it follows the site's
  theme *toggle* and not only the operating system's preference — the two
  disagree the moment a visitor overrides it, and a logo that ignores the switch
  is the most visible possible way to look broken.
*/

export function Mark({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 945 655"
      className={className}
      role="img"
      aria-label="Zence"
      focusable="false"
    >
      <g fill="var(--color-brand-ink)">
        <rect x="45" y="0" width="66" height="96" rx="3" />
        <rect x="834" y="0" width="66" height="96" rx="3" />
        <rect x="834" y="449" width="66" height="74" rx="3" />
        <rect x="0" y="93" width="945" height="82" rx="3" />
        <polygon points="599,175 773,175 435,429 260,429" />
        <polygon points="455,242 637,242 267,520 84,520" />
        <rect x="0" y="520" width="945" height="80" rx="3" />
        <rect x="45" y="597" width="66" height="58" rx="3" />
        <rect x="834" y="597" width="66" height="58" rx="3" />
      </g>
      <polygon points="455,242 684,242 435,429 206,429" fill="var(--color-brand-accent)" />
    </svg>
  );
}
